stages:
  - deploy

deploy_finance_be_dev:
  stage: deploy
  tags:
    - development
  script:
    - echo "🚀 Memulai sinkronisasi ke folder deployment..."
    
    # 0. AMBIL ALIH KEPEMILIKAN
    - sudo chown -R alpha-team:gitlab-runner /home/alpha-team/development/client/wajira/finance-be
    
    # 1. Safe directory
    - git config --global --add safe.directory /home/alpha-team/development/client/wajira/finance-be
    
    # 2. Masuk folder
    - cd /home/alpha-team/development/client/wajira/finance-be
    
    # 3. Sync dari development
    - echo "🔄 Fetching latest code from development..."
    - git fetch origin development
    - git reset --hard origin/development
    # 3. Sync dari development
    - echo "🔄 Fetching latest code from development..."
    - git fetch origin development
    - git reset --hard origin/development
    
    # 4. Docker Build & Up
    - echo "🐳 Rebuilding Docker containers..."
    - docker compose up -d --build
    
    # 5. Permission Laravel
    - echo "🔓 Setting permissions..."
    # 5. Permission Laravel
    - echo "🔓 Setting permissions..."
    - docker exec wajira-finance-backend chown -R www-data:www-data /app/storage /app/bootstrap/cache
    - docker exec wajira-finance-backend chmod -R 775 /app/storage /app/bootstrap/cache
    
    # 6. Wait DB
    - echo "⏳ Menunggu database siap..."
    # 6. Wait DB
    - echo "⏳ Menunggu database siap..."
    - sleep 15
    
    # 7. Laravel Command
    - echo "✨ Running artisan..."
    - docker exec wajira-finance-backend bash /app/dummy-fresh.sh
    # - docker exec wajira-finance-backend php artisan migrate:fresh --seed
    # - docker exec wajira-finance-backend php artisan db:seed --class=DummyDataSeeder
    # - docker exec wajira-finance-backend php artisan db:seed --class=MainCompanyWarehouseSeeder
    # - docker exec wajira-finance-backend php artisan optimize:clear
    
    - echo "✅ Wajira Finance BE Dev is Live!"
    
    - echo "✅ Wajira Finance BE Dev is Live!"
    
  only:
    - development
    - development