stages:
  - build
  - test
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

# =========================
# GLOBAL BEFORE SCRIPT
# =========================
default:
  before_script:
    - 'echo "🚧 Runner: $(hostname)"'
    - 'echo "👤 User: $(whoami)"'
    - 'docker --version || true'

# =========================
# BASE TEMPLATE
# =========================
.default-dev: &default-dev
  tags:
    - stagging
    - deraly
    - hq
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'

.default-prod: &default-prod
  tags:
    - cloud
    - wajira
    - production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'


# =========================
# DEVELOPMENT PIPELINE
# =========================
build-dev:
  <<: *default-dev
  stage: build
  script:
    - echo "Build development (optional)"

test-dev:
  <<: *default-dev
  stage: test
  script:
    - echo "Testing development (optional)"

deploy-dev:
  <<: *default-dev
  stage: deploy
  environment:
    name: staging
  script:
    - echo "Deploy to staging"


# =========================
# PRODUCTION PIPELINE
# =========================
build-prod:
  <<: *default-prod
  stage: build
  script:
    - echo "Build production (optional)"

test-prod:
  <<: *default-prod
  stage: test
  script:
    - echo "Testing production (optional)"

deploy-prod:
  <<: *default-prod
  stage: deploy
  environment:
    name: production
  script:
    - echo "🚀 Deploy Production Started"

    - |
      sudo -u wajira-team bash << 'EOF'
      set -e

      cd /home/wajira-team/production/finance-api

      echo "📥 Pull latest code"
      git pull origin master

      echo "📁 Setup & Fix Permissions (Host)"
      chmod -R 775 storage bootstrap/cache

      echo "🐳 Rebuild container"
      docker compose -f docker-compose.prod.yaml up -d --build

      echo "⏳ Wait container ready"
      sleep 5

      echo "⚙️ Run install script"
      docker exec wajira-finance-backend bash prod-install.sh
      EOF

    - echo "✅ Deploy Done"

  when: manual